In [1]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_excel('uniprotkb_HUMAN_AND_reviewed_true_2023_09_09.xlsx')

In [8]:
df

            Entry   Entry Name Interacts with
0      A0A024B7W1   POLG_ZIKVF            NaN
1      A0A068B6Q6   CA18_CONBE            NaN
2      A0A076FFM5   F8H1_OCIBA            NaN
3      A0A087X1C5  CP2D7_HUMAN            NaN
4      A0A0A1I6E7  NDB4S_ANDCR            NaN
...           ...          ...            ...
51687      Q9ZMP3   Y189_HELPJ            NaN
51688      Q9ZMR9   Y162_HELPJ            NaN
51689      Q9ZMW2   HRCA_HELPJ            NaN
51690      X6R8D5  GUCNB_HUMAN            NaN
51691      X6R8R1  ST15B_HUMAN            NaN

[51692 rows x 3 columns]

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51692 entries, 0 to 51691
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Entry           51692 non-null  object
 1   Entry Name      51692 non-null  object
 2   Interacts with  13632 non-null  object
dtypes: object(3)
memory usage: 1.2+ MB

In [46]:
type(df['Interacts with'].iloc[2233])

str

In [52]:
df[df['Entry Name'] == 'POLG_ZIKVF']

        Entry  Entry Name Interacts with
0  A0A024B7W1  POLG_ZIKVF            NaN

In [55]:
df.isnull().sum()

Entry                 0
Entry Name            0
Interacts with    38060
dtype: int64

In [79]:
df[~df['Interacts with'].isnull()]

            Entry   Entry Name                                  Interacts with
6      A0A0B4J2F0  PIOS1_HUMAN                                          Q96S66
7      A0A0B4J2F2  SIK1B_HUMAN  Q9BRT9; Q68G74; Q14696; P78337; Q9NRG1; P62072
18     A0A0G2KTI4  S12A2_DANRE                                      A0A0G2KTI4
26     A0A0H3JRU9    PYC_STAAM                                      A0A0H3JRU9
49     A0A0U1RRE5   NBDY_HUMAN                                  Q9NPI6; Q6P2E9
...           ...          ...                                             ...
50543      P0DPF6  CB27B_HUMAN                                          D3DTS7
50774      P35977      C_MEASA                                          Q60680
50955      Q1HVD3  BTRF1_EBVA8                                          P03219
51349      Q77PU6    U90_HHV6Z                                          P52630
51576      Q9H7T3  CJ095_HUMAN                                          Q96E22

[13632 rows x 3 columns]

In [12]:
df['Entry'].unique().shape

(51692,)

In [62]:
df['Interacts with'].unique().shape

(12615,)

In [13]:
df['Entry'].nunique()

51692

In [78]:
df.iloc[0]['Interacts with']

False

In [110]:
st = set()
def extract_uniques(row):
#     print(row['Entry'], end=' ')

#     st.add(row['Entry'])
    print(row.shape[0])
    
    for i in range(row.shape[0]):
        st.add(row[i])

In [111]:
extract_uniques(df['Entry'])

51692

In [113]:
len(st)

51692

In [114]:
new_df = df[~df['Interacts with'].isnull()]

In [140]:
new_df['Interacts with'].iloc[5]

'Q8N111; Q99653; Q9NWW5; Q4G0J3; Q9NX58; Q8NEJ9; O43251-6; O00767; Q16637; Q5BJD5'

In [148]:
st2 = set()
def extract_uniques2(row):
    print(row.shape[0])
    sum=0
    for i in range(row.shape[0]):
        l=[]
        proteins = row.iloc[i]
        if ';' in proteins:
            l = proteins.split("; ")
        else:
            l.append(proteins);
            
        sum+=len(l)
        
        for i in l:
            st2.add(i)
            
    print(sum)

In [149]:
extract_uniques2(new_df['Interacts with'])

13632
173376

In [150]:
len(st2)

18486

In [151]:
len(st)

51692

In [153]:
len(st.union(st2))

57928

In [154]:
final_st = st.union(st2)

In [155]:
len(final_st)

57928

In [156]:
final_st

{'O75385',
 'P0DTC4',
 'Q92522',
 'P0DUX0',
 'Q8NEZ3',
 'P09104',
 'Q1JNS7',
 'P16773',
 'Q8WXE1',
 'P05000',
 'Q9GZU7',
 'C0MFQ4',
 'Q2NEH4',
 'P32970',
 'Q9BYG7',
 'P69299',
 'Q0CJ60',
 'Q9QSP2',
 'Q9ZJR4',
 'Q5VXU9',
 'P65886',
 'Q9H4B8',
 'P14735-1',
 'Q5VWG9',
 'Q8GM56',
 'P9WGF1',
 'Q7ZWJ4',
 'Q95ML5',
 'Q5PJH0',
 'P63135',
 'Q6UW10',
 'Q5PGW7',
 'Q7Z628',
 'P21009',
 'P27313',
 'A5D903',
 'Q04837',
 'B9E903',
 'C4Z2T4',
 'Q8A102',
 'Q62193',
 'P18097',
 'F1QYJ6',
 'Q9NS85',
 'PRO_0000448014 [O91464]',
 'Q6NSB6',
 'Q6DPJ8',
 'B9EB64',
 'Q9NQ31',
 'Q6ZSZ5',
 'P01567',
 'P35971',
 'U3NEE3',
 'Q32P28',
 'A4GE42',
 'A7I002',
 'Q6ZTI0',
 'Q5I0X7',
 'Q5U5X8',
 'Q8E1T5',
 'P05162',
 'Q9BVC3',
 'Q8NCA9',
 'Q6G338',
 'Q8A677',
 'P39092',
 'Q1J7B2',
 'Q8N7R0',
 'A6NKC9',
 'C0MEH6',
 'Q96P67',
 'Q9UGM1',
 'Q9LFR7',
 'Q96PY6',
 'P28728',
 'Q5R5V0',
 'Q8NDH3',
 'A1AJ78',
 'Q1JK40',
 'Q9H6U6-2',
 'Q96AT1',
 'P0DOH5',
 'P16661',
 'P0DOU5',
 'PRO_0000240177 [O40955]',
 'Q9BT22',
 'A0Q8I1',
 'P41264',
 'Q9ZJU5',
 'P9WIF5',
 'Q8N1A6',
 'O75343',
 'Q6G398',
 'Q6G3Z3',
 'Q6G546',
 'P89446',
 'P42785',
 'Q9IPJ8',
 'P0CQ87',
 'P28159',
 'P33447',
 'Q4L4H9',
 'Q9H633',
 'Q8VCE6',
 'Q6Y4S4',
 'Q94514',
 'P33076',
 'C4Z5N7',
 'Q96PN7',
 'Q8TD31-1',
 'Q75WM6',
 'Q86VF5-3',
 'Q9YWQ2',
 'P0DOM6',
 'Q86UT5-2',
 'Q8IXJ6-2',
 'Q1E180',
 'Q6A6V2',
 'A6NIJ9',
 'Q4L703',
 'Q5PD20',
 'Q5PIU7',
 'Q9ULE4',
 'P01229',
 'Q4L6S8',
 'P9WNB3',
 'Q924W6',
 'O95199',
 'Q9NUR3',
 'P31260-2',
 'Q93050',
 'A8MVA2',
 'P0C775',
 'F1QNV4',
 'Q7SXP4',
 'Q96CS3',
 'Q5DJT8',
 'Q9QZH6',
 'P31721',
 'P40145',
 'O68704',
 'Q01083',
 'A0A0H3JNB0',
 'Q12824-2',
 'Q8IX94',
 'P12473',
 'Q8CX15',
 'Q56EB0',
 'P0CO85',
 'Q2HRD4',
 'Q98185',
 'A1AGK1',
 'P20531',
 'Q9JI59',
 'Q9WC64',
 'Q8DYV7',
 'Q12874',
 'Q6PBX5',
 'O75541-2',
 'Q1JAN3',
 'Q91090',
 'O15350',
 'C1H986',
 'Q86SY8',
 'Q8TAP8',
 'P48761',
 'P06162',
 'A6NH11',
 'Q9NZW5',
 'Q1JJ37',
 'Q0BPK2',
 'A6NKB5-5',
 'O97302',
 'Q9H582',
 'P12269',
 'Q9Y5Y0',
 'C7B247',
 'P42681',
 'P0CP26',
 'Q9DB07',
 'Q3TNS5',
 'O15156',
 'Q6ZNK6',
 'P84813',
 'Q2NFC3',
 'Q9JLY0',
 'P15678',
 'Q9ULI3',
 'P23515',
 'B9E8C4',
 'Q8DWR3',
 'P05866',
 'Q9H4P4',
 'Q64429',
 'A9Q1L0',
 'P24025',
 'Q6ZNG1',
 'Q96S94-5',
 'Q9NYF0',
 'Q8A5W2',
 'P60672',
 'Q83GP4',
 'Q8BT20',
 'C5JJG5',
 'Q9ULJ7-2',
 'Q9NZM1',
 'P18875',
 'C1G0X0',
 'Q495M9',
 'A1A9R2',
 'A7ZCN6',
 'A4H213',
 'Q9BZR8',
 'Q67207',
 'O60499-1',
 'P21004',
 'P31689',
 'O55040',
 'O14981',
 'P18965',
 'B3EWH0',
 'P79185',
 'P51447',
 'Q95LY5',
 'Q9UW02',
 'F1QPC3',
 'P50797',
 'Q7L4I2-2',
 'Q60953',
 'Q58D68',
 'Q8IYA2',
 'C4JYM4',
 'P62140',
 'Q70HW3',
 'Q9BTL3',
 'P04296',
 'Q9ZJP6',
 'A6LEH9',
 'P13073',
 'Q6P587-2',
 'Q25641',
 'Q9NS56',
 'Q5PL86',
 'P0DKF2',
 'Q8WP32',
 'P32121',
 'Q3SXP7',
 'C0MEW5',
 'Q9JJY8',
 'P0CG00',
 'P13158',
 'P24408',
 'P20532',
 'A7GZJ6',
 'Q6G1G7',
 'A0A0H3LAC5',
 'Q5DRF5',
 'A0A7H0DN17',
 'Q1HVF6',
 'Q7L8C5',
 'C0MH11',
 'Q86WC4',
 'P49221',
 'Q1DLP2',
 'F5HG68',
 'P0CP68',
 'Q01581',
 'Q96RI0',
 'P0DKV0',
 'Q1JIV9',
 'P12369',
 'P22694-2',
 'Q49A26-4',
 'Q4L9V8',
 'Q14980',
 'Q4L522',
 'A8PRN6',
 'Q13219',
 'C4Z9R8',
 'P09301',
 'Q12797',
 'P03429',
 'P62502',
 'Q2KIQ4',
 'Q1J992',
 'P0DOV1',
 'Q18C71',
 'Q15506',
 'A2D5K9',
 'Q1J8D8',
 'Q6P3G4',
 'P58467',
 'Q9NTN9-3',
 'Q9V6Q2',
 'Q96DZ1',
 'Q9JI18',
 'A4H245',
 'Q94A32',
 'Q8NHA6',
 'Q9H0W9-4',
 'A1AE55',
 'Q8IYS5',
 'P22105-1',
 'Q182F0',
 'P60010',
 'Q8WUT1',
 'A0A0A1I6E7',
 'Q43125',
 'Q710U6',
 'Q8IXW7',
 'Q96NU1',
 'Q14EA9',
 'Q8N2Y8',
 'P38219',
 'P22085',
 'Q1J459',
 'C0HL86',
 'A7I277',
 'Q9Y2B0',
 'Q96L12',
 'Q96EP9',
 'Q0VG73',
 'Q5PC78',
 'Q67380',
 'Q1LVN1',
 'P67813',
 'Q8NGS7',
 'A5UL76',
 'P0C7W6',
 'Q96DN7',
 'Q5AIB8',
 'Q99M96',
 'Q8JN08',
 'P07245',
 'Q9H649',
 'Q8E238',
 'P08908',
 'P17755',
 'Q9BXW3',
 'Q4WLC9',
 'Q84V39',
 'Q8AA95',
 'P41223',
 'Q96MX6',
 'Q9ZM59',
 'Q8BND3',
 'P05042',
 'Q13416',
 'P50226',
 'P35372',
 'P20868',
 'Q4L7B0',
 'G3FEX6',
 'PRO_0000449647 [P0DTC2]',
 'Q13045',
 'Q76V07',
 'Q8LW54',
 'Q9DC77',
 'P25294',
 'Q4VBH4',
 'A7ZFY7',
 'P06700',
 'P21054',
 'Q9UHC1-2',
 'O75881',
 'P50279',
 'Q13569',
 'Q9Y4X0',
 'P0CL89',
 'P26083',
 'Q86U28',
 'Q8B0I3',
 'F1QF89',
 'P35771',
 'Q7T012',
 'Q96BW9',
 'P21433',
 'Q9GZQ8',
 'O15539',
 'Q2T4N1',
 'Q969U6-1',
 'Q9UNW1',
 'A0A146B485',
 'Q9NZN8',
 'Q01339',
 'A6LEZ7',
 'Q9W6R1',
 'P28223',
 'P52376',
 'Q64770',
 'P13943',
 'A0A7H0DN33',
 'Q5TA31',
 'Q8NGH8',
 'Q8BX09',
 'O75971',
 'A0A2H3CZX2',
 'Q6P0D7',
 'Q86SQ6',
 'B3SRY2',
 'Q8N9A8',
 'P83547',
 'C4ZD61',
 'Q5VSL9',
 'Q9UIJ5',
 'P24706',
 'Q6PIZ9',
 'Q863A0',
 'Q9WT55',
 'I6W9F2',
 'P28340',
 'P51034',
 'Q5T7P3',
 'P0C724',
 'A6L1Z3',
 'P51492',
 'P46593',
 'Q8G4X4',
 'Q9ZKB3',
 'O95922',
 'P41208',
 'Q9ZJL8',
 'P34897',
 'Q6MX50',
 'Q05789',
 'Q99697-2',
 'Q16585',
 'P08651-5',
 'P09603',
 'Q9VLU5',
 'Q92499-1',
 'Q6ZS72',
 'Q9NUD5',
 'Q76RD1',
 'Q9BZW8',
 'Q56A40',
 'Q96LI9',
 'P0C573',
 'O35587',
 'P0CR09',
 'Q6DGQ1',
 'P20700',
 'Q15459',
 'Q5A7S7',
 'Q9BT76',
 'Q1JKA0',
 'P91643',
 'P00514',
 'Q5PL63',
 'P04611',
 'P33203',
 'P50607',
 'Q9BRL6',
 'Q1JNA9',
 'Q8IYW5',
 'P68402',
 'D4AKL6',
 'A0PG75',
 'A3KPW7',
 'Q2NHE1',
 'Q15019-1',
 'P02775',
 'O89085',
 'Q9BTV4',
 'Q18CD3',
 'Q12370',
 'Q0GBX5',
 'P35711-4',
 'Q189R2',
 'P62195',
 'Q8B9Q8',
 'Q98176',
 'Q8DXT0',
 'P0DQW3',
 'Q9NXS2-3',
 'Q8G4S7',
 'A5UN55',
 'P0C7H7',
 'A5HBG1',
 'P07758',
 'P08172',
 'P57729',
 'Q80WK2',
 'Q4L6T4',
 'A7GZK3',
 'Q2GD33',
 'P0CG62',
 'P04053',
 'Q2TBT5',
 'Q8QGW7',
 'Q18BB8',
 'Q9Z325',
 'Q1JN21',
 'Q3KST0',
 'Q9Y277',
 'Q9ZN30',
 'Q8G3G3',
 'Q83G91',
 'A6R620',
 'Q8NEF3-2',
 'Q9H3M0',
 'P20639',
 'Q6ZRR7',
 'O94876',
 'Q96NR3',
 'Q98277',
 'O75891',
 'P10636-2',
 'Q2GH19',
 'Q96SB8',
 'O60870',
 'P13222',
 'Q8IY57-5',
 'Q187N7',
 'Q1J7A5',
 'P25713',
 'Q28789',
 'P0DUJ5',
 'Q1JL27',
 'Q5PK30',
 'Q0D2J5',
 'A0A2R9YJI3',
 'R4JQT5',
 'P18658',
 'Q8IYL2',
 'Q7XZT8',
 'P27824-2',
 'Q9FUW6',
 'A6L030',
 'Q923S6',
 'Q5PJ62',
 'P04201',
 'Q62953',
 'C0MG79',
 'P0A9T0',
 'Q9GKU6',
 'A4ZCW2',
 'O12165',
 'P30622-2',
 'Q9HB63',
 'O60333-3',
 'Q8CHN3',
 'A5UL38',
 'Q6DP29',
 'A8Z6J5',
 'Q9HCB6',
 'P03341',
 'Q6UIM2',
 'Q8R4H9',
 'A5PMY6',
 'P09592',
 'Q9JMK2',
 'P24593',
 'A0A0B4J1U7',
 'A7H668',
 'A7ZEJ1',
 'P0CN20',
 'O57405',
 'Q8DXS7',
 'Q9NWC5',
 'Q96JT2',
 'Q7Z3G6',
 'P35555',
 'L7XDS4',
 'P0CQ03',
 'P50690',
 'Q68396',
 'Q4L2Z4',
 'Q8G415',
 'A0ELI2',
 'C0MFQ7',
 'P0DN81',
 'P13640',
 'Q8SPW1',
 'A7H0G1',
 'Q4L4A6',
 'Q86TG7-2',
 'B2RI48',
 'Q05133',
 'A6L078',
 'P05927',
 'Q9UN73',
 'O43155',
 'P03518',
 'Q1JM45',
 'Q94424',
 'P26073',
 'P78352-2',
 'Q6A6R0',
 'Q913D4',
 'Q9ZM50',
 'Q5KC16',
 'F5HAI6',
 'P25116',
 'Q86TI2',
 'Q96PH6',
 'Q9P7C9',
 'A1A9L8',
 'Q9WU03',
 'Q6A833',
 'P0DPP9',
 'B9E8E3',
 'Q8WNV3',
 'P0DTL5',
 'P57721-2',
 'O75023',
 'Q27874',
 'Q63932',
 'Q15334',
 'Q5PN01',
 'Q9NWX5',
 'A0Q4I0',
 'Q96Q40',
 'Q4L7Z3',
 'Q8BT35',
 'A6NNT2',
 'Q54BX3',
 'A4GZ95',
 'Q182X3',
 'Q2NEQ4',
 'Q4L5M5',
 'Q9QWV9',
 'Q8NI22',
 'Q6P602',
 'Q8TF74',
 'Q180P9',
 'Q1MTD4',
 'Q99542',
 'Q15811-1',
 'Q8BNI4',
 'P13533',
 'P20061',
 'Q8IUH2',
 'P34910-2',
 'Q1HVF7',
 'Q1J9U7',
 'B4R9C5',
 'P26551',
 'O95255',
 'Q5PJB2',
 'Q01534',
 'O94829',
 'P27286',
 'P09291',
 'A1ACW2',
 'Q0CEZ9',
 'A5IS16',
 'C0MEG6',
 'Q5T9L3-1',
 'P22626',
 'Q4L4X7',
 'Q9H816',
 'Q15389-2',
 'Q80V31',
 'Q5XKR4',
 'P0C744',
 'P0CO90',
 'B4RC48',
 'Q5PM07',
 'Q9P2E7',
 'Q9WTN0',
 'Q6G1A8',
 'O75122',
 'Q5GS20',
 'Q7SX85',
 'Q5PLL9',
 'Q96T59',
 'P09707',
 'Q12798',
 'Q5DRA9',
 'P17900',
 'Q9J6K8',
 'P30895',
 'A7GXU2',
 'Q1JLT7',
 'P07141',
 'P26208',
 'Q8NI35',
 'Q2HR75',
 'P27352',
 'Q6E213',
 'Q8N158',
 'Q8R4N0',
 'P09343',
 'Q9ZLW6',
 'Q9Y6M1',
 'Q5RJ20',
 'O43822',
 'Q6A9M5',
 'Q9UKE5',
 'Q2GGS4',
 'B9E707',
 'Q9QB93',
 'A6L0W6',
 'Q5PG61',
 'P97288',
 'Q9NYZ4',
 'P39876',
 'Q8IXQ4',
 'Q7KQJ9',
 'Q13794',
 'Q7Z309',
 'A6NES4',
 'Q8NI36',
 'O94903',
 'Q8IAW3',
 'Q66793',
 'Q9WTV1',
 'Q1J9V2',
 'Q9JS44',
 'Q8QZV0',
 'Q09056',
 'Q9NTX7',
 'P16220',
 'F5HDA4',
 'Q2GKG5',
 'C1HDW2',
 'P04426',
 'A0A024A2C9',
 'A6L744',
 'P29175',
 'P86922',
 'A2T733',
 'Q5PFR8',
 'Q99640-2',
 'A6L9V0',
 'Q9ZKY5',
 'Q8VHS2',
 'A7GY16',
 'Q1JC67',
 'Q9Y2T4',
 'P12967',
 'Q8IYX1',
 'P66143',
 'Q7LG56',
 'A0A087WSX0',
 'O43561-2',
 'P56706',
 'A0A1D8PGY0',
 'Q9NYX4',
 'Q9UKC9',
 'Q8IUR5-4',
 'P0C023',
 'Q15041',
 'Q2HRB4',
 'Q6DI40',
 'Q5RGQ8',
 'Q9JKL5',
 'Q5XIE8',
 'Q4KN05',
 'P35908',
 'Q9UQF0',
 'Q86T03',
 'Q9Y365',
 'Q5PDH1',
 'B0V2N1',
 'P31025',
 'Q9EQ00',
 'A0Q768',
 'A2T6Y4',
 'Q6SW29',
 'Q86UU1',
 'Q8NGC8',
 'O24282',
 'Q6G1Z7',
 'Q1J9C6',
 'Q4L5N4',
 'Q6G1C0',
 'Q9UHA4',
 'M1L9M3',
 'C0HLA9',
 'Q9Z2J0',
 'P17658',
 'Q91ZY1',
 'Q7ZTA7',
 'P21097',
 'C0M824',
 'Q6P9A2',
 'Q2GGH9',
 'Q99742',
 'Q8A294',
 'A5UNI4',
 'Q67212',
 'Q6DPE6',
 'P19320',
 'A4U7B2',
 'F5HF90',
 'Q9H7U1',
 'F1R237',
 'Q5T0T0',
 'Q99607',
 'P46992',
 'A2T7D7',
 'A0A0H3PEK7',
 'Q4JWT5',
 'Q6UXF1',
 'O08795',
 'Q8HXM1',
 'Q9ZLJ1',
 'Q8ABV5',
 'P08709',
 'P02679',
 'Q6TFL4',
 'Q96IX5',
 'F5HAZ3',
 'A7H537',
 'C5PAD0',
 'P20512',
 'A1A8D9',
 'Q6FYB9',
 'Q9Y5J7',
 'Q18C74',
 'A7H623',
 'F1R520',
 'A0Q628',
 'P0C0P6',
 'Q13952',
 'Q92623',
 'O95257',
 'Q5PHT4',
 'P38822',
 'Q8NG27',
 'Q9ZJD5',
 'B4RB35',
 'Q8G603',
 'A2S1Q7',
 'Q9W2P0',
 'O14737',
 'P45973',
 'Q9GZX6',
 'P27913',
 'O60231',
 'A0A0B5A8P4',
 'A0Q4K8',
 'Q6ZV77',
 'Q83G48',
 'Q03157',
 'A3RK74',
 'Q6G027',
 'O15165-2',
 'A1AEU6',
 'Q4L9J7',
 'P36856',
 'P0CG04',
 'P29178',
 'Q717R9',
 'Q8C8K3',
 'A1ABZ5',
 'B9E8Q0',
 'Q6ZVL8',
 'Q12060',
 'Q9Z0G9',
 'Q0HD60',
 'Q6BAA4',
 'Q7Z6Z7-2',
 'Q18BW7',
 'P38789',
 'O00408',
 'Q3YBM2',
 'Q86WN1',
 'Q56A73',
 'Q15742-2',
 'A7ZC36',
 'Q6NUJ1',
 'P23881',
 'Q99KQ4',
 'Q4L739',
 'P59632',
 'Q9P104',
 'Q9UF11',
 'Q6ZNC4',
 'Q06217',
 'P84475',
 'Q9NX57',
 'Q6A8Q1',
 'Q96AY2',
 'A0AVI2',
 'P52549',
 'Q96HU1',
 'Q02577',
 'Q91ZU9',
 'Q8WWU5',
 'Q26228',
 'A6QUM7',
 'P49768',
 'Q9ZKF7',
 'Q96L96',
 'A1A774',
 'Q4L3I4',
 'P47810',
 'P26012',
 'Q76KP1',
 'P0C701',
 'P98140',
 'Q8K3Y6',
 'Q14696',
 'Q9Y2R0',
 'Q2NHW1',
 'A5UKB4',
 'Q8IYF3-3',
 'Q2NH88',
 'Q9JLN9',
 'P38646',
 'Q01196-8',
 'Q9UBP5',
 'P26362',
 'B4URF7',
 'O43169',
 'Q9BQS7',
 'O35604',
 'P0DMW5',
 'Q925G2',
 'Q3KSP3',
 'P52701',
 'P0C6H3',
 'Q13555',
 'P0CM29',
 'Q2T9J0-1',
 'A1AAA9',
 'A2CEM9',
 'P15879',
 'P21127',
 'A1AFY9',
 'Q8V4Y0',
 'O94855',
 'Q07108',
 'P79238',
 'P16228',
 'Q0R5R0',
 'B0S5G3',
 'A5A6I5',
 'Q99MQ3',
 'Q9NPP4',
 'Q5TIA1',
 'O95336',
 'P01040',
 'Q7A655',
 'A7J399',
 'Q13296',
 'Q80DN6',
 'O43298',
 'Q04875',
 'P49901',
 'Q7L7V1',
 'A7I1V8',
 'Q8AA22',
 'Q07279',
 'P21737',
 'Q5PEH1',
 'B9EK46',
 'Q1J578',
 'Q8N841',
 'Q9Y2E4',
 'Q12285',
 'Q8BGY9',
 'Q8C9S8',
 'Q96M95-2',
 'P70271',
 'Q1JAF7',
 'Q18CH7',
 'P11678',
 'Q2F9P4',
 'O81209',
 'Q8NC96',
 'Q9H1M3',
 'P67191',
 'P26687',
 'C0MDJ9',
 'Q6ZW61',
 'Q01844-3',
 'Q2TBV3',
 'Q8A7V7',
 'P62072',
 'Q9H115',
 'Q9NPG1',
 'Q8N201',
 'Q0P5K3',
 'Q5PFQ4',
 'A0A075B6J2',
 'Q4L6A3',
 'P0C161',
 'A0A1L6K371',
 'Q5ZPR3',
 'Q9NQC3-5',
 'P0C8M3',
 'P13861-2',
 'Q1JCL3',
 'Q52LW3',
 'P30777',
 'P92919',
 'Q8NF91',
 'O00541',
 'Q8CJ53',
 'A0A2I4QAG8',
 'Q4G0T1',
 'Q80Z25',
 'A4GE45',
 'A6H8M9',
 'Q9NQB0-10',
 'Q2M3G4',
 ...}

In [158]:
final_df = pd.DataFrame(final_st,columns=['All_unique_proteins'])

In [167]:
df.shape

(51692, 3)

In [166]:
final_df.shape

(57928, 1)

In [170]:
final_df

      All_unique_proteins
0                  O75385
1                  P0DTC4
2                  Q92522
3                  P0DUX0
4                  Q8NEZ3
...                   ...
57923              Q86VH2
57924              Q01469
57925              Q5VZP5
57926              O95169
57927              Q9WUA5

[57928 rows x 1 columns]

In [172]:
file_name = 'Unique_proteins.xlsx'
final_df.to_excel(file_name)
# final_df.to_csv(file_name)